# Generated by Django 4.0.4 on 2022-07-23 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stationname', models.CharField(max_length=100, null=True)),
                ('datatime', models.CharField(max_length=100, null=True)),
                ('so2value', models.CharField(max_length=10, null=True)),
                ('covalue', models.CharField(max_length=10, null=True)),
                ('o3value', models.CharField(max_length=10, null=True)),
                ('no2value', models.CharField(max_length=10, null=True)),
                ('pm10value', models.CharField(max_length=10, null=True)),
                ('khaivalue', models.CharField(max_length=10, null=True)),
                ('khaigrade', models.CharField(max_length=10, null=True)),
                ('so2grade', models.CharField(max_length=10, null=True)),
                ('cograde', models.CharField(max_length=10, null=True)),
                ('o3grade', models.CharField(max_length=10, null=True)),
                ('no2grade', models.CharField(max_length=10, null=True)),
                ('pm10grade', models.CharField(max_length=10, null=True)),
                ('lat', models.FloatField(blank=True, default=None, null=True)),
                ('lng', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
    ]
