# Generated by Django 4.0.6 on 2022-07-27 16:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_phone_number_user_num_user_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='num',
            field=models.SmallIntegerField(default=2, null=True, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
